config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  
  devise_for :users

 resources :events do
  resources :comments
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base

	has_many :comments
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!



  def index
  	@comments = current_user.comments
  	@comments = Comment.all
  end

  def new
  	@comment = Comment.new
  end

  def create
  	@comment = Comment.new(comment_params.merge(user_id:current_user.id))
  	@comment.event_id = params[:event_id]

  	if @comment.save
  		redirect_to event_path(params[:event_id])
  	else
  		render :new
  	end
  end

  def edit
  	@comment = Comment.find(params[:id])
  end

  def update
  	@comment = Comment.find(params[:id])

  	if @comment.update_attributes(comment_params)
  		redirect_to comments_path
  	else
  		render :edit
  	end
  end




  private

  def comment_params
  	params.require(:comment).permit(:body)
  end





end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index

  		if params[:id].present?
		@events = Event.where(name: params[:id])
		else
		@events = Event.all
		end
	end
 

  def show
  	@event = Event.find(params[:id])
  	@comment = Comment.new
  	@comments = @event.comments
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/comments/edit.html.erb
<%= form_for @comment do |form| %>
	<%= form.label :body %>
	<%=form.text_area :body %><br>

	<%= form.submit 'Update' %>

	<% end %>

app/views/comments/index.html.erb
<%= link_to "Post a Comment", new_comment_path %>

<%= simple_table_for @comments, with: CommentsTable %>

app/views/comments/new.html.erb
<%= form_for @comment do |form| %>
	<%= form.label :body %>
	<%=form.text_area :body %><br>

	<%= form.submit 'Post' %>

	<% end %>

app/views/events/index.html.erb
<h1>Please see below for all events:</h1>

<%= form_tag '', method: 'GET' do %>
	<%= text_field_tag(:id, params[:id], { placeholder: 'Search Query'}) %>
	<%= submit_tag 'Search' %>
<% end %>

<% @events.each do |event| %>
<%= event.name %><br>
<%= event.description %><br>
<%= event.date %><br>
<%= link_to "view details", event_path(event) %><br><br>
<% end %>

app/views/events/show.html.erb
<% @comments.each do |comment| %>
<%= comment.body %><br>

<% end %>

<%= simple_form_for [@event, @comment] do |form| %>
<%= form.input :body %>
<%= form.submit %>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Conferring" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Conferring</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>